modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/Carro1001/MonsterHunter-NewWorld/issues" #optional
logoFile=""
credits="Life" #optional
authors="carro1001, AlexVR"
[[mods]] #mandatory
modId="mhnw" #mandatory
version="1" #mandatory
displayName="Monster Hunter: New World" #mandatory
description='''
A Monster Hunter themed mod for Minecraft
'''
