modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/Carro1001/MonsterHunter-NewWorld/issues" #optional
logoFile=""
credits="Life" #optional
authors="carro1001, AlexVR"
[[mods]] #mandatory
modId="mhnw" #mandatory
version="1" #mandatory
displayName="Monster Hunter: New World" #mandatory
description='''
A Monster Hunter themed mod for Minecraft
'''

[[dependencies.mhnw]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[46,)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.mhnw]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mhnw]]
modId = "geckolib"
mandatory = true
versionRange = "[4.2,)"
ordering = "BEFORE"
side = "BOTH"