#!/usr/bin/env node
// Regenerates the Giant Jawblade's charge-pose models and the overrides that select them.
// This is derived, reproducible data (same spirit as src/generated/resources): don't hand-edit the
// output, change the constants here and rerun (`node tools/gen_jawblade_charge_models.js`).
//
// WHY SO MANY FILES: a charge pose has to lean smoothly, and the only render hook that knows WHICH
// ENTITY is holding the weapon is an item property function -- a custom renderer (BEWLR) and a
// baked-model wrapper both receive the stack without its holder, so on a server they would pose
// every player's weapon from the local player's charge. Property functions drive discrete model
// overrides, so "smooth" is spelled "more steps", exactly as vanilla spells it for bow_pulling_0..2.
// STEPS is simply how fine that ramp is.
//
// STEPS must stay equal to GiantJawbladeItem.CHARGE_POSE_STEPS; a GameTest fails if they drift.
"use strict";

const fs = require("fs");
const path = require("path");

const STEPS = 48;
// Degrees of backward lean at a full charge, added to the artist's own resting rotation.
const MAX_LEAN_DEGREES = 65;
// Poses that are actually held in a hand. GUI, ground and item-frame keep the resting model.
const HAND_CONTEXTS = [
    "thirdperson_righthand",
    "thirdperson_lefthand",
    "firstperson_righthand",
    "firstperson_lefthand",
];

const root = path.join(__dirname, "..");
const itemDir = path.join(root, "src/main/resources/assets/mhnw/models/item");
const basePath = path.join(itemDir, "giant_jawblade.json");
const base = JSON.parse(fs.readFileSync(basePath, "utf8"));

// Drop any previously generated step models so a lower STEPS never leaves orphans behind.
for (const file of fs.readdirSync(itemDir)) {
    if (/^giant_jawblade_charge_\d+\.json$/.test(file)) {
        fs.unlinkSync(path.join(itemDir, file));
    }
}

const overrides = [];
for (let step = 1; step <= STEPS; step++) {
    const progress = step / STEPS;
    const lean = MAX_LEAN_DEGREES * progress;
    const display = {};
    for (const context of HAND_CONTEXTS) {
        const resting = base.display[context] || {};
        const rotation = (resting.rotation || [0, 0, 0]).slice();
        rotation[0] = Math.round((rotation[0] + lean) * 100) / 100;
        display[context] = Object.assign({}, resting, { rotation });
    }
    const model = {
        comment:
            "GENERATED by tools/gen_jawblade_charge_models.js -- do not hand-edit. Charge pose " +
            step + " of " + STEPS + " (" + Math.round(progress * 100) + "% wound up). Inherits " +
            "geometry, texture and every non-hand display context from mhnw:item/giant_jawblade.",
        parent: "mhnw:item/giant_jawblade",
        display: display,
    };
    fs.writeFileSync(
        path.join(itemDir, "giant_jawblade_charge_" + step + ".json"),
        JSON.stringify(model, null, 2) + "\n"
    );
    // Predicates match on "at least this value", so the last one that matches wins.
    overrides.push({
        predicate: { "mhnw:charge": Math.round(progress * 10000) / 10000 },
        model: "mhnw:item/giant_jawblade_charge_" + step,
    });
}

base.overrides = overrides;
fs.writeFileSync(basePath, JSON.stringify(base, null, 2) + "\n");
console.log("wrote " + STEPS + " charge poses and their overrides (max lean " +
    MAX_LEAN_DEGREES + " degrees)");
